name: Feature
description: Adding or changing functionality of the program.
title: "[FEATURE]: "
labels: ["feature"]
assignees:
  - Harrison-Blair
body:
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      placeholder: |
        As a <type of user>,
        I would like <feature>,
        because it would <reasoning>.
    validations:
        required: true
  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      description: How much effort/work will this take?
      options:
        - 0
        - 1
        - 2
        - 3
        - 5
        - 8
        - 13
        - not sure
  - type: textarea
    id: functional-requirements
    attributes:
      label: Functional Requirements
      description: What, not how
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What functionality will change for the user after this story?
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: anything that might help implementation efforts
      placeholder: |
        Documentation
          - Link1
          - Link2

        Wiki
          - Link1

        Reference
          - Link1
          - Link2
